Small modification

diff --git a/hm3/lsrm b/hm3/lsrm
--- a/hm3/lsrm
+++ b/hm3/lsrm
@@ -1,6 +1,10 @@
 #!/bin/sh
 
 # List all the files in the trashbin.
+if [ $# -ge 1 ]; then
+	echo "$0: Cannot have any arguments!"
+	exit 1
+fi
 if [ -z $TRASH ]; then
 	echo "Environment variable TRASH is not set yet!"
 	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
diff --git a/hm3/srm2/durm b/hm3/srm2/durm
--- a/hm3/srm2/durm
+++ b/hm3/srm2/durm
@@ -1,6 +1,11 @@
 #!/bin/sh
 
 # Show the total size of all the files in the trashcan.
+if [ $# -ge 1 ]; then
+        echo "$0: Cannot have any arguments!"
+        exit 1
+fi
+
 if [ -z $TRASH ]; then
 	echo "Environment variable TRASH is not set yet!"
 	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
diff --git a/hm3/unrm b/hm3/unrm
--- a/hm3/unrm
+++ b/hm3/unrm
@@ -1,6 +1,14 @@
 #!/bin/sh
 
 # Recover the file specified from the trashcan to current directory.
+for i in "$@"
+do
+	if [[ $i == -* ]]; then
+		echo "$0: Cannot have any options!"
+		exit 1
+	fi
+done
+
 if [ -z $TRASH ]; then
 	echo "Environment variable TRASH is not set yet!"
 	echo "Please add the following varibale to .bash_profile or .profile or .login at the ~/ directory: "
